### ISSUE TITLE
When using the template type `'SimpleModule'` it adds unnecessary configuration 

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#277]
When using the template type `'SimpleModule'` it **should not** add:

In RequiredModules.psd1
```
    'DscResource.Common'        = 'latest'
    'DscResource.Test'          = 'latest'
    'DscResource.AnalyzerRules' = 'latest'
    xDscResourceDesigner        = 'latest'
    'DscResource.DocGenerator'  = 'latest'
```

In build.yaml

```
  hqrmtest:
    - DscResource_Tests_Stop_On_Fail
```

When using the template type `'SimpleModule'` it **should ask for values** for:

In azure-pipelines.yml it should ask for the name of the default branch.

```
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
```

In azure-pipelines.yml it should ask for the name of the account name that owns the upstream repository (so that it does not try to deploy in forks).

```
        contains(variables['System.TeamFoundationCollectionUri'], 'synedgy')
```

**Comment by johlju** [comment]
It does not add a GitVersion.yaml. and it should ask for the name of the default branch in the line `regex: ^main$`:

```
branches:
  master:
    tag: preview
    regex: ^main$
  pull-request:
    tag: PR
  feature:
    tag: useBranchName
    increment: Minor
    regex: f(eature(s)?)?[\/-]
    source-branches: ['master']
  hotfix:
    tag: fix
    increment: Patch
    regex: (hot)?fix(es)?[\/-]
    source-branches: ['master']
```

**Comment by johlju** [comment]
It should ask for the name of the default branch and add the following to the tasks _publishRelease_ and _sendChangelogPR_ in the pipeline job _Deploy\_Module_.

```
ReleaseBranch: main
MainGitBranch: main
```

Example:

```
          - task: PowerShell@2
            name: publish_release
            displayName: 'Publish Release'
            inputs:
              filePath: './build.ps1'
              arguments: '-tasks publish'
              pwsh: true
            env:
              GitHubToken: $(GitHubToken)
              GalleryApiToken: $(GalleryApiToken)
              ReleaseBranch: main
              MainGitBranch: main
          - task: PowerShell@2
            name: send_changelog_PR
            displayName: 'Send CHANGELOG PR'
            inputs:
              filePath: './build.ps1'
              arguments: '-tasks Create_ChangeLog_GitHub_PR'
              pwsh: true
            env:
              GitHubToken: $(GitHubToken)
              ReleaseBranch: main
              MainGitBranch: main
```
