### ISSUE TITLE
Pester 5 tests seems to run twice when paths are not specified in build.yml

### ISSUE THREAD

**Issue by pjstam** [gaelcolas/Sampler#337]
### Problem description

Hi there,
It looks like the pester tests run twice when the Path: is left default (commented). Workaround is to specify the paths.
Regards,
Peter

``` yml
Pester:
  OutputFormat: NUnitXML
  # Excludes one or more paths from being used to calculate code coverage.
  ExcludeFromCodeCoverage:

  # If no scripts are defined the default is to use all the tests under the project's
  # tests folder or source folder (if present). Test script paths can be defined to
  # only run tests in certain folders, or run specific test files, or can be use to
  # specify the order tests are run.
  Path:
  # - tests/QA/module.tests.ps1
  - tests/QA **when commenting, it runs twice**
  - tests/Unit **when commenting, it runs twice**
  # - tests/Integration
  ExcludeTag:
  #  - helpQuality
  #  - FunctionalQuality
  #  - TestQuality
```

### Verbose logs

```text
The output shows the run twice.
```

### How to reproduce

Create a New-SampleModule with 'simplemodule' type.

### Expected behavior

It should run once.

### Current behavior

It's running twice.

### Suggested solution

It's ok for me to just uncomment the build.yml, maybe solving it in the future.

### Operating system the target node is running

```text
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module version used

```text
Latest  0.112.0
```
