### ISSUE TITLE
Merge code coverage parameters are incorrect in template 

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#359]
### Problem description

These two parameters should not be under the key `Pester:`
https://github.com/gaelcolas/Sampler/blob/d19ef072498ac9df81a3839b0b7a502a066f2235/Sampler/Templates/Build/build.yaml.template#L242-L243

They should be under a key `CodeCoverage:`

```yaml
CodeCoverage:
  CodeCoverageFilePattern: JaCoCo_Merge.xml # the pattern used to search all pipeline test job artifacts
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml # the file that is created for the merged code coverage
```

### Verbose logs

```text
n/a
```

### How to reproduce

Using the current template will never make the Merge-task to succeed.

### Expected behavior

Correct configuration in the build configuration.

### Current behavior

Using the current template will never make the Merge-task to succeed.

### Suggested solution

Modify the plaster template to include `CodeCoverage:` key,

### Operating system the target node is running

```text
n/a
```

### PowerShell version and build the target node is running

```text
n/a
```

### Module version used

```text
n/a
```
